############################################
### Packages that are used in this study ###
############################################

### Single-cell analysis, bulk analysis (CCLE transcriptomics and proteomics) & synergic analysis
library(Seurat)
library(SeuratData)
library(SeuratDisk)
library(dplyr)
library(DESeq2)
library(devtools)
library(xlsx)
library(readxl)
library(DoubletFinder)
library(harmony)
library(scater)
library(data.table)
library(MLP)
library(Matrix)
library(igraph)
library(dittoSeq)
library(CellChat)
library(escape)
library(AUCell)
library(NMF)
library(ggalluvial)
library(genefu)
library(GSEABase)
library(xtable)
library(rmeta)
library(org.Hs.eg.db)
library(Biobase)
library(caret)
library(tidyverse)
library(PCAtools)
library(patchwork)
library(clusterProfiler)
library(GSVA)
library(scales)
library(synergyfinder)

### Visualization
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(ggthemes)
library(ggsignif)
library(ggtext)
library(gridExtra)
library(grid)
library(gridtext)
library(patchwork)
library(VennDiagram)
library(ComplexHeatmap)
